#
# Freescale Management Complex (MC) bus drivers
#
# Copyright (C) 2014 Freescale Semiconductor, Inc.
#
# This file is released under the GPLv2
#

# MC DPIO driver
obj-$(CONFIG_FSL_MC_DPIO) += dpio/
