#
# Makefile for Freescale Soc specific device drivers.
#

obj-$(CONFIG_LS1_SOC_DRIVERS)	+= ls1/
obj-$(CONFIG_QUICC_ENGINE)	+= qe/
obj-$(CONFIG_CPM)		+= qe/
obj-$(CONFIG_FSL_GUTS)		+= guts.o
obj-$(CONFIG_LS_SOC_DRIVERS) += ls2-console/
