obj-$(CONFIG_FSL_DCE_TESTS) += dce_simple_perf_tester.o
dce_simple_perf_tester-objs := dce_perf_simple.o

obj-$(CONFIG_FSL_DCE_TESTS) += dce_simple_sf_perf_tester.o
dce_simple_sf_perf_tester-objs := dce_sf_perf_simple.o
