#
# Makefile for the Freescale network device drivers.
#

obj-$(CONFIG_FSL_DPAA2_ETH)	+= ethernet/
obj-$(CONFIG_FSL_DPAA2_MAC)	+= mac/
obj-$(CONFIG_FSL_DPAA2_ETHSW)	+= ethsw/
obj-$(CONFIG_FSL_DPAA2_EVB)	+= evb/
obj-$(CONFIG_FSL_DPAA2_DCE)	+= dce/
obj-$(CONFIG_PTP_1588_CLOCK_DPAA2)	+= rtc/
