obj-y += test_frame_helpers.o

#obj-$(CONFIG_FSL_DCE_TESTS) += dce_chunk_comp_def_cf_tester.o
#dce_chunk_comp_def_cf_tester-objs := common/test_frame_helpers.o dce_chunk_comp_def_cf_test.o

#obj-y += performance_simple/

