#
# Makefile for the Freescale DPAA2 DCE driver
#
# Copyright (C) 2015 Freescale Semiconductor, Inc.
#
# This file is released under the GPLv2
#

obj-$(CONFIG_FSL_DPAA2_DCE) += fsl-dce-api.o
fsl-dce-api-objs	:= dpdcei-drv.o dpdcei.o dce-fd.o dce-fcr.o dce-scf-compression.o dce-scf-decompression.o dce-fd-frc.o dce.o
